### ISSUE TITLE
[Feature][EPIC] Add mac m1 as supported host

### ISSUE THREAD

**Issue by adrianriobo** [adrianriobo/qenvs#15]
- [x] #20 
- [x] use command to post setup instead of user data 
- [x] #23 (vnc port)
- [x] include some [notification mechanism](https://docs.aws.amazon.com/sns/latest/dg/sns-email-notifications.html)
- [x] #24
- [x] #34 
- [x] #40 
- [x] create custom AMIS https://aws.amazon.com/blogs/compute/building-amazon-machine-images-amis-for-ec2-mac-instances-with-packer/
